kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "gradle-jenkins-slave" 
spec:
  source: 
    type: "Git"
    git:
      uri: "https://github.com/andrewskripnik/docker.git"
  strategy: 
    type: "Docker"
    dockerStrategy:
      dockerfilePath: Docker/gradle-jenkins-slave/Dockerfile
  output: 
    to:
      kind: "DockerImage"
      name: "docker-registry.default.svc:5000/cicd/gradle-jenkins-slave:latest"
  postCommit: 
      script: "ls /usr/libexec/"
