kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "gradle-jenkins-slave" 
  annotations:
    description: Modifies the openshift/jenkins-slave-base-centos7 to run as Jenkins slave
  labels:
    app: gradle-jenkins-agent
    name: gradle-slave
    template: gradle-jenkins-agent
  namespace: cicd
spec:
  source: 
    type: "Git"
    git:
      ref: master
      uri: "https://github.com/andrewskripnik/docker.git"
  strategy: 
    type: "Docker"
    dockerStrategy:
      dockerfilePath: Docker/gradle-jenkins-slave/Dockerfile
  output: 
    to:
      kind: "DockerImage"
      name: "docker-registry.default.svc:5000/cicd/gradle-jenkins-slave:latest"
  postCommit: 
      script: "ls /usr/libexec/"
