kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "java-1.8"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/andrewskripnik/docker.git"
    contextDir: "Docker/lukspay-otp-deploy" 
  strategy:
    type: "Docker"
    dockerStrategy:
      dockerfilePath: Docker/lukspay-otp-deploy/Dockerfile
  output:
    to:
      kind: "DockerImage"
      name: "docker-registry.default.svc:5000/test/lukspay-otp:latest"
  postCommit:
      script: "ls /"

