kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "s2i-gradle4.10-jdk8" 
spec:
  source: 
    type: "Git"
    git:
      uri: "https://github.com/andrewskripnik/docker.git"
  strategy: 
    type: "Docker"
    dockerStrategy:
      dockerfilePath: Docker/s2i-gradle-builder/grdale4-jdk8/Dockerfile
  output: 
    to:
      kind: "DockerImage"
      name: "docker-registry.default.svc:5000/test/s2i-jdk8-gradle4.10:latest"
  postCommit: 
      script: "ls /usr/libexec/"
